/*
* A component that lists all of the user's bingo sheets
* as they have them stored in local storage.
* Sheets have:
*   - UUID (generated by uuidv4 upon creation) 
*   - Title (user input, defaults to "Untitled")
*
* The user can:
*   - Create a new sheet
*   - Delete an existing sheet
*   - Edit the title of an existing sheet
*   - View the bingo sheet (the BingoGrid component)
*/

import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import BingoGrid from './BingoGrid';
import bingoData from '../bingoData.json'; // Adjust the path as needed
import {createShareableLink, importSheetData, createNewSheet} from '../utils/storage';

/**
 * A component that give the user a selector of `bingoDataJsonKeys` to choose from
 * and a button to create a new sheet with the selected `bingoDataJsonKey`.
 */
const NewBingoSheetSelector = ({ addSheet }) => {
    const bingoDataJsonKeys = Object.keys(bingoData);
    const [selectedKey, setSelectedKey] = useState(bingoDataJsonKeys[0]);
    
    return (
        <div>
        <div>Create a new bingo sheet:</div>
        <select
            value={selectedKey}
            onChange={(e) => setSelectedKey(e.target.value)}
        >
            {bingoDataJsonKeys.map((key) => (
            <option key={key} value={key}>
                {key}
            </option>
            ))}
        </select>
        <button onClick={() => addSheet(selectedKey)}>Create</button>
        </div>
    );
};

const BingoSheetsList = () => {
    const [sheets, setSheets] = useState({});
    const [isEditing, setIsEditing] = useState(false);
    const [isCreatingNewSheet, setIsCreatingNewSheet] = useState(false);
    
    useEffect(() => {
        const sheets = JSON.parse(localStorage.getItem('sheets')) || {};
        setSheets(sheets);
    }, []);
    
    useEffect(() => {
        localStorage.setItem('sheets', JSON.stringify(sheets));
    }, [sheets]);
    
    const addSheet = (selectedKey) => {
        const newSheet = createNewSheet(selectedKey);
        setSheets({ ...sheets, [newSheet.id]: newSheet });
    };
    
    const deleteSheet = (id) => {
        const newSheets = { ...sheets };
        delete newSheets[id];
        setSheets(newSheets);
    };
    
    const updateSheet = (updatedSheet) => {
        setSheets({ ...sheets, [updatedSheet.id]: updatedSheet });
    };

    const updateCell = (updatedCell) => {
        const sheet = sheets[updatedCell.sheetId];
        const updatedCells = sheet.cells.map((cell) => {
            if (cell.id === updatedCell.id) {
                return updatedCell;
            }
            return cell;
        }
        );
        const updatedSheet = { ...sheet, cells: updatedCells };
        updateSheet(updatedSheet);
    };

    const [activeSheetId, setActiveSheetId] = useState(null);

    // Function to change the active sheet
    const toggleSheet = (sheetId) => {
        console.log(`toggling sheet ${JSON.stringify(sheetId)}`)
        // console the sheet's data
        const sheet = sheets[sheetId];
        if (!sheet) {
            console.log(`no sheet found with id ${sheetId}`)
        } else {
            console.log("sheetData", JSON.stringify(sheet))
        }
        setActiveSheetId(sheetId);
    };

    const handleShareClick = () => {
        const activeSheetData = sheets[activeSheetId];
        if (activeSheetData) {
            const link = createShareableLink(activeSheetData);
            // Handle the link as needed (e.g., copy to clipboard, display in a modal, etc.)
            console.log(link); // For testing purposes
        }
    };

    useEffect(() => {
        const sheetsFromStorage = JSON.parse(localStorage.getItem('sheets')) || {};
        const queryParams = new URLSearchParams(window.location.search);
        const encodedData = queryParams.get("data");

        if (encodedData) {
            console.log('Creating sheet from query param', {
                encodedData,            
            })
            const importedSheet = importSheetData(encodedData);
            console.log('importedSheet', importedSheet)
            if (importedSheet && !sheetsFromStorage[importedSheet.id]) {
                // Add the imported sheet if it doesn't already exist
                const updatedSheets = { ...sheetsFromStorage, [importedSheet.id]: {
                    ...importedSheet,
                    title: importedSheet.title + ' (Imported)',
                }
            };
                setSheets(updatedSheets);
            }
            window.history.replaceState(null, null, window.location.pathname);
        } else {
            // Load sheets from localStorage if no query param
            setSheets(sheetsFromStorage);
        }
    }, []);


    return (
        <Container>
        <SheetList>
            <NewSheetPlaceHolder
                onClick={() => setIsCreatingNewSheet(true)}
            >New</NewSheetPlaceHolder>
            {Object.entries(sheets).map(([sheetId, sheet]) => (
            <SheetListEntry 
                key={sheetId}
                onClick={() => {
                    setIsCreatingNewSheet(false);
                    toggleSheet(sheetId)}
                }
                activeSheetId={activeSheetId}
                sheetId={sheetId}
            >
                <SheetTitle
                    xzvalue={sheet.title}
                    type="text" 
                    value={sheet.title} 
                    isEditing={isEditing}
                    onChange={(e) =>
                        updateSheet({ ...sheet, title: e.target.value })
                    }
                    onKeyDown={(e) => {
                        if (e.key === 'Enter') {
                            e.preventDefault();
                            e.target.blur();
                        }
                    }}
                    onFocus={() => setIsEditing(true)}
                    onBlur={() => setIsEditing(false)}
                />
                    <DeleteX onClick={() => deleteSheet(sheet.id)}>
                        X
                    </DeleteX>
            </SheetListEntry>
            ))}
        </SheetList>
        <DisplaySheet>
            <div className="share-icon" onClick={handleShareClick}>
                Share {/* Replace with an actual icon */}
            </div>
            {!isCreatingNewSheet && 
                <BingoGrid 
                    sheetId={activeSheetId} 
                    sheet={sheets[activeSheetId]} 
                    updateCell={updateCell}
                />}
            {isCreatingNewSheet && <NewBingoSheetSelector addSheet={addSheet} />}
        </DisplaySheet>
        </Container>
    );
};

export default BingoSheetsList;

// Container holds the sheet list on the left side of the screen in a row,
// and the BingoGrid on the right side of the screen.
const Container = styled.div`
display: flex;
flex-direction: row;
`;

// SheetList displates all of the sheets in a single row
// along the left side of the screen.
// The right side of the screen is the BingoGrid.
const SheetList = styled.div`
  display: flex;
  flex-direction: column; /* Changed from row to column */
  align-items: center;
  width: 20%; /* Set a fixed width or use percentage */
`;

// Takes up the right side of the screen, about 80% of the width.
// Goes to the bottom of the screen.
const DisplaySheet = styled.div`
    position: relative;
    width: 100%;
    background-color: #000;
    min-height: 100vh;

    .share-icon {
        position: absolute;
        top: 10px;
        right: 10px;
        cursor: pointer;
        /* Style your icon here */
    }
`;

const DeleteX = styled.div`
cursor: pointer;
font-size: 20px;
font-weight: bold;
color: #fff;
cursor: pointer;
margin-right: 10px;

&:hover {
    transform: scale(1.2)
}
`;

const entryHeight = '50px';
const entryWidth = '100%';

const SheetListEntry = styled(({ sheetId, activeSheetId, ...props }) => <div {...props} />)`
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-between; /* Adjusted for space between title and delete button */
  width: ${entryWidth};
  height: ${entryHeight};
  margin-bottom: 10px; /* Margin for spacing between entries */
  border-radius: 10px;
  &:hover {
    background-color: #333;
  }
  ${props => props.activeSheetId === props.sheetId && `background-color: #333;`}
`;

const NewSheetPlaceHolder = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  width: ${entryWidth};
  height: ${entryHeight};
  margin-bottom: 10px; /* Consistent margin with SheetListEntry */
  &:hover {
    background-color: #333;
  }
`;

const SheetTitle = styled(({ xzvlue, isEditing, ...props }) => <textarea {...props} />)`
    max-height: 100px;
    border: none;
    background: none;
    outline: none;
    color: #fff;
    resize: none; // Disable resizing
    font-size: 16px;
    overflow: auto; // Allow scrolling
    margin: 20px; // Add some margin
    word-wrap: ${props => props.isEditing ? 'none' : 'break-word'};
    word-break: ${props => props.isEditing ? 'break-all' : 'normal'};
    white-space: ${props => props.isEditing ? 'pre' : 'normal'};
    overflow-wrap: ${props => props.isEditing ? 'break-word' : 'normal'};
`;

// Path: src/components/BingoGrid.js